### ISSUE TITLE
ShellCheck creates a few small issues

### ISSUE THREAD

**Issue by shavs** [theaquacadet/pillager#4]
# Introduction
[ShellCheck](http://www.shellcheck.net/) is a Bash script linter, which will ensure that the script is correct, and also warns of issues using some simple commands.

### Line 2: No quotes around `$HOME/.pillager`
Line is:
```bash
[[ -d $HOME/.pillager ]] || mkdir $HOME/.pillager
```

Line should be:
```bash
[[ -d $HOME/.pillager ]] || mkdir "$HOME/.pillager"
```

### Line 10 - `read` is missing `-r` flag to avoid mangling backspaces
Line is `read LINE`, should be `read -r LINE`.

### Line 13 - Two variables are missing the double quotes around them
Line reads:
```bash
wget -r -np -nc -e robots=off -c --reject index.html,index.html* ${LINK} -P $SAVEPATH
```

Line should be:
```
wget -r -np -nc -e robots=off -c --reject index.html,index.html* "${LINK}" -P "$SAVEPATH"
```

## Changed file
For brevity - this is the complete file change, after amendments.

```bash
#!/bin/bash
[[ -d $HOME/.pillager ]] || mkdir "$HOME/.pillager"
#Download directory
currentdir="$PWD"
SAVEPATH="${1-$currentdir}"
#Save link adresses to /home/*/.pillager/list
list=$HOME/.pillager/list
echo -n "Link to pillage: "

read -r LINK

echo "$LINK" >> "$list"
wget -r -np -nc -e robots=off -c --reject index.html,index.html* "${LINK}" -P "$SAVEPATH"

echo "Finished. Yar."
```

**Comment by theaquacadet** [comment]
Thanks! will update it now.
